# Generated by Django 4.2.4 on 2023-10-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('short_description', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('cover_photo', models.TextField(null=True)),
                ('page_photo1', models.TextField(null=True)),
                ('page_photo2', models.TextField(null=True)),
                ('review_1', models.IntegerField(null=True)),
                ('review_2', models.IntegerField(null=True)),
                ('review_3', models.IntegerField(null=True)),
                ('review_4', models.IntegerField(null=True)),
                ('review_5', models.IntegerField(null=True)),
                ('master_review', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000, null=True)),
                ('published_date', models.DateField(null=True)),
                ('listed_date', models.DateTimeField(auto_now_add=True)),
                ('genre_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_genre_1', to='genre.genre')),
                ('genre_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_genre_2', to='genre.genre')),
            ],
        ),
    ]
