# Generated by Django 4.2.4 on 2023-10-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('logo', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
                ('established_date', models.DateField()),
            ],
        ),
    ]
